language: node_js
node_js: 'stable'
script:
  - npm run build
cache:
  directories:
    - node_modules
deploy:
  provider: s3
  access_key_id:
    secure: HBbx25E9IctSKtViCEAsw1qv13jtpRR74bTm92cPFUGitW/pqHieB22zZi7rc2SmjydsR2bFrBXqqaGe1JSCGlYnBpGWa0mHhim3QVg7QGxrkjjAM0jUjm/mozKLFokhp07Vau/vhEp212Y1zyNbhcTr6017kth5sLaGCHPjREOeIkrGqdGsJucUgOExDQgDyv/ds2GCzrdlLeQQOxaZs/NdEoJoYdlv6OXNAyTbVI8VaF5VIJ6Dcj5+JXqcB28dKa/8TxAnqEKpwkvJVCLJNI6yuFRjoet7YpMTglXF+UCEIvHmmJppdpnY5elVmgWkI6DpC0VK10mB7ibwevfpB7vzCH0GkH8UPjqQbvONND74DLWQcfRJpNMIngZIxmkxIrBOkv/cpSVf4BIdwaGYRA1iVyyWp+XCLuNZYTWS+j/HQoZJIanixzTece8OuXP3TOcbYUOBB+e3hU2eT1a+sPWSSSxqIfqpb7cxz2vSrBzLLnMFAwG2qvlr7S11hbJ1Q5RbQktilKlsGlxHUGnbPMY+7QBs5zCdLGUTDE0TxNcZSCADYRa034udOGzkoLKsP/k3/3ksr7fbWvCq1jGZ5gNzWCXqjC7KsCtzYgfp0oClJIz5qTcv+isLc+4tlDkQehAnzpa0YfrWQ1G9pnw2jaskTatelUKl+mlDHoLLjJA=
  secret_access_key:
    secure: XsuLQdnJQ97PENVKMUBVC3bwOSi2EH0rz3tDT1/LcMUAZ+8JYtokkt4g4zNosx3A9occctT4igCIX5Hk+BcD8yKw2DtZWPXPJJVk4KFWqivfFjAKgA0oMMMg500FVbYNmyC33BH0noHxN5UUwPYSNJ/o0Mro06PEKxYnxXrfnftLxD6S4ThtCcU+T9yWzZ4FA5V7vK1vsk0iVkTJnsO9wBaHqbj0r92R3fYdjgQEZtHMevKMYq1tXx+CAX6c3LrTPyDc2Aq2op+/3xDGTTu7wiCjMmImwi3QZDZxAnilP2MNvJ6dfi2U9hkhMcp1LyNZ7VE3TKeywnw1zxSp2UY468g65IlQOfaa+wy5yhOm0r8qWlXn6ANawUOPII5Z4YiiP99mnCrhOPooic2WFPhps8Rglj8rZLoJ5UesP3jAoTKl0yKmZ16C3AU1JJau8fTHmtO0Edc+GGuKgwf7TouxvFJzetwvNad1AiRd+6KcTNGvqFwGwxswUgOHo7zgNct3eQaFrkuIF3XzF/+074nS0V8HHzOpxCssuo4qDAWFnXYbj02L6anuxEnz8nIf4QP/VZeq4MR2nw9hIkoLEMxNI478lmB02dBW6H2ATvQWWQOULN7hPSQ3ZVxVEUxCEhTlVj4jnSR4mETtJRa9RSBMa8NzLZtJwVm0HzvnyDZzLoE=
  bucket: 'jennytran.ninja'
  skip_cleanup: true
  acl: public_read
  region: eu-west-1
  local_dir: build
  on:
    branch: master
