language: node_js
node_js: 'stable'
script:
  - npm run build
cache:
  directories:
    - node_modules
deploy:
  provider: s3
  access_key_id: 'AKIA3DRBGY7Q7VKVATFF'
  secret_access_key:
    secure: 'C+hRlWOsFETKbYWpwawydcvZsjOEE7WoFdCsZk682qcAoZB5z+EMjKSc3lZTmFfc8IxF0mhQ1wboRyphTB0rPmjlICjNTGXQu2IkKmTB1OqzDFASgkiz5TCbQ12YioH8BBDWFMJt0aujMt+AbUB4M0tNMTABmjNHgXbr34l+7M+fjQS3cegOHX0yhy6irosEIKY8mZv553R8cbAaQnpEjZaX+flfExGqM7Mwj7t1mgbVn0aITfLvOXO5suorx2abRGnNgK3+uNdSdr65eXU2I1nUL7RIKUSXkoEBkoS9aV2L1ZXNnl/+QJRaxySx/kSKX2VlrXvyMoK9yC3w0yrurBZIhSFqFMB7bpDFyT7lpsA/OUn104K1kRQhbJH/X//Lk0iLR7CcaVUFmOVQluD5r/ASzqysL4344svDV2AiE9dJq3XACRXOhrdT+7zx/th1vSeJxeyvV28IvaKG/4FqtrRlFYvnbBnBrqXuaCyJmSjOdPg9SAVlX0mQHI4hJK7uNAz0cumxnl5r/fix3sAGdMattRlXi3cAt/rF4d/ggSUcEGujGcKECA3J8JD2Fkx9eFdGbtFp5/Av0+TibSuac8Lxa+YT4XMlBaaWHSioRP9TKVH5PLPRCNsu3aJ3AGGGa30WWpC0mF3PWW9eo8quxrlOAjOWJpRfuu9sDeS4710='
  bucket: 'jennytran.ninja'
  skip_cleanup: true
  acl: public_read
  region: eu-west-1
  local_dir: build
  on:
    branch: master
